name: Manually build on Github Actions

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Dockerfile path to be built'
        required: true
        default: 'docker-images/ubuntu20.04/cuda-11.1.1/ffmpeg-4.4/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
#     if: "join(fromJSON(github.event.inputs.path), '') != ''" # preoceed only when we have something to build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Get path and create tag
        id: dockerfile
        run: |
          filepath=${{ github.event.inputs.path }};
          echo "path=$filepath" >> $GITHUB_OUTPUT;
          workdir=$(dirname $filepath);
          echo "workdir=${workdir}" >> $GITHUB_OUTPUT;
          tag=$(echo $filepath | sed 's/docker-images\/ubuntu\([0-9\.]*\).*\/cuda-\([0-9]*\)[\.]*\([0-9]*\)[^/]*\/ffmpeg-\([0-9\.]*\)[^/]*.*Dockerfile/\4-cu\2\3/' | sed 's/\(.*\)\/Dockerfile/\1/' | sed 's/\//-/g');
          echo "tag=${tag}" >> $GITHUB_OUTPUT;
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_PACKAGES_TOKEN }}
      -
        name: Build and push Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ steps.dockerfile.outputs.workdir }}
          file: ${{ steps.dockerfile.outputs.path }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.dockerfile.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.dockerfile.outputs.tag }}
